### ISSUE TITLE
Exception trying to hash Mongo ObjectID

### ISSUE THREAD

**Issue by siboulet** [puleos/object-hash#49]
I'm trying to use object-hash to hash an object contain a Mongo ObjectID object.

The following code:

```js
var ObjectID = require('mongodb').ObjectID;
var hash = require('object-hash');

console.log(hash(new ObjectID()));
```

Throws:

```js
/x/node_modules/bson/lib/bson/objectid.js:347
     return this.id[3] | this.id[2] << 8 | this.id[1] << 16 | this.id[0] << 24;
                   ^

TypeError: Cannot read property '3' of undefined
    at ObjectID.Object.defineProperty.get [as generationTime] (/x/node_modules/bson/lib/bson/objectid.js:347:20)
    at /x/node_modules/object-hash/index.js:237:33
    at Array.forEach (native)
    at Object._object (/x/node_modules/object-hash/index.js:233:21)
    at Object.dispatch (/x/node_modules/object-hash/index.js:183:30)
    at /x/node_modules/object-hash/index.js:237:18
    at Array.forEach (native)
    at Object._object (/x/node_modules/object-hash/index.js:233:21)
    at Object.dispatch (/x/node_modules/object-hash/index.js:183:30)
    at hash (/x/node_modules/object-hash/index.js:126:10)
```

Any help would be greatly appreciated.

Thanks

**Comment by henricazottes** [comment]
I had the same error when using an object containing a populated attribute (I'm using mongoose). But thanks to your question I know now that it comes from the ObjectId, and I found an answer:  use ``toObject()`` method and the hash will work :)

**Comment by addaleax** [comment]
Yeah, this is tricky – this invokes a getter on the ObjectID prototype, not the object itself … you can work around this by using `respectType: false`, but that is going to give you different hashes.

**Comment by kiwenlau** [comment]
I have the same problem, solved by converting ObjectId to String.：

```javascript
hash(new ObjectID().toString())
```

**Comment by nateevans** [comment]
You can handle this fairly easily using the `replacer` option. 
https://github.com/puleos/object-hash/blob/master/test/replacer.js

```
var replacer = function(value) {
      try {
        return value.toString();
      } catch (e) {
        return value;
      }
    };

hash(objectWithObjectIds, { replacer: replacer });
```

This should handle any object ids, even nested down the object tree. Might want to fine tune the replacer function to specifically act on ObjectId types.

**Comment by men232** [comment]
```js
import mongoose from 'mongoose';

const ObjectId = mongoose.Types.ObjectId;

const replacer = function(value) {
	if (value instanceof ObjectId) {
		value = value.toString();
	}

	return value;
};

hash(objectWithObjectIds, { replacer: replacer });
```

**Comment by bybraveHQ** [comment]
Root cause for the record: with the default `respectType: true`, object-hash injects `prototype`, `__proto__` and `constructor` as extra keys and serializes the whole prototype graph of the value — which fires every getter defined on foreign prototypes. BSON's `ObjectID` had getters that assumed internal state, hence the crash.

I maintain an actively developed fork ([@bybrave/object-hash2](https://github.com/bybraveHQ/object-hash2)); in 4.0.0 `respectType` uses a compact type marker (constructor identity) instead of walking the prototype graph, so foreign getters are never invoked and `ObjectID`-like classes hash fine. Bonus: skipping that walk makes default-options hashing ~2x faster.
